import type { MapConfig } from '../mapTypes';
import {
  ZONE_APARTMENTS,
  ZONE_DEPOT,
  ZONE_EAST_ROW,
  ZONE_MARKET,
  ZONE_START,
  ZONE_SUBSTATION,
  ZONE_WEST_ROW,
} from './cityLayout';

export const CITY_MAP: MapConfig = {
  id: 'city',
  name: 'Ashvale',
  description:
    'An abandoned residential grid on the edge of town. Fight the rounds through the streets, open the barricades, restore power at the substation.',
  roundBased: true,
  playerSpawn: { x: 0, y: 0, z: 96, yaw: 0 },

  zones: [
    { id: ZONE_START, name: 'Elm Street', unlockedAtStart: true },
    { id: ZONE_WEST_ROW, name: 'West Row', unlockedAtStart: false },
    { id: ZONE_EAST_ROW, name: 'East Row', unlockedAtStart: false },
    { id: ZONE_MARKET, name: 'Market Square', unlockedAtStart: false },
    { id: ZONE_APARTMENTS, name: 'Kestrel Apartments', unlockedAtStart: false },
    { id: ZONE_DEPOT, name: 'Depot Yard', unlockedAtStart: false },
    { id: ZONE_SUBSTATION, name: 'Substation', unlockedAtStart: false },
  ],

  barriers: [
    {
      id: 'bar_start_west',
      name: 'Collapsed Scaffold',
      zone: ZONE_START,
      unlocksZone: ZONE_WEST_ROW,
      cost: 750,
      x: -86,
      y: 0,
      z: 74,
      yaw: 0,
      width: 11,
      height: 3.4,
      thickness: 0.6,
      requiresPower: false,
    },
    {
      id: 'bar_start_east',
      name: 'Chained Gate',
      zone: ZONE_START,
      unlocksZone: ZONE_EAST_ROW,
      cost: 750,
      x: 86,
      y: 0,
      z: 74,
      yaw: 0,
      width: 11,
      height: 3.4,
      thickness: 0.6,
      requiresPower: false,
    },
    {
      id: 'bar_start_market',
      name: 'Barricaded Crossing',
      zone: ZONE_START,
      unlocksZone: ZONE_MARKET,
      cost: 1000,
      x: 0,
      y: 0,
      z: 30,
      yaw: 0,
      width: 11,
      height: 3.4,
      thickness: 0.6,
      requiresPower: false,
    },
    {
      id: 'bar_west_market',
      name: 'Alley Shutter',
      zone: ZONE_WEST_ROW,
      unlocksZone: ZONE_MARKET,
      cost: 1000,
      x: -44,
      y: 0,
      z: 53,
      yaw: Math.PI / 2,
      width: 5,
      height: 3,
      thickness: 0.5,
      requiresPower: false,
    },
    {
      id: 'bar_east_market',
      name: 'Service Shutter',
      zone: ZONE_EAST_ROW,
      unlocksZone: ZONE_MARKET,
      cost: 1000,
      x: 44,
      y: 0,
      z: 53,
      yaw: Math.PI / 2,
      width: 5,
      height: 3,
      thickness: 0.5,
      requiresPower: false,
    },
    {
      id: 'bar_market_apartments',
      name: 'Courtyard Door',
      zone: ZONE_MARKET,
      unlocksZone: ZONE_APARTMENTS,
      cost: 1250,
      x: 0,
      y: 0,
      z: -20,
      yaw: 0,
      width: 11,
      height: 3.4,
      thickness: 0.6,
      requiresPower: false,
    },
    {
      id: 'bar_apartments_depot',
      name: 'Depot Fence Gate',
      zone: ZONE_APARTMENTS,
      unlocksZone: ZONE_DEPOT,
      cost: 1250,
      x: -43,
      y: 0,
      z: -78,
      yaw: 0,
      width: 5,
      height: 3,
      thickness: 0.5,
      requiresPower: false,
    },
    {
      id: 'bar_apartments_substation',
      name: 'Substation Gate',
      zone: ZONE_APARTMENTS,
      unlocksZone: ZONE_SUBSTATION,
      cost: 1250,
      x: 43,
      y: 0,
      z: -78,
      yaw: 0,
      width: 5,
      height: 3,
      thickness: 0.5,
      requiresPower: false,
    },
  ],

  spawnZones: [
    { id: 'sp_start_alley_w', zone: ZONE_START, x: -29, z: 60, radius: 3.5, weight: 1 },
    { id: 'sp_start_alley_e', zone: ZONE_START, x: 29, z: 60, radius: 3.5, weight: 1 },
    { id: 'sp_start_house_w', zone: ZONE_START, x: -51, z: 84, radius: 3, weight: 1 },
    { id: 'sp_start_house_e', zone: ZONE_START, x: 51, z: 84, radius: 3, weight: 1 },
    { id: 'sp_start_road_s', zone: ZONE_START, x: 0, z: 112, radius: 4, weight: 1.2 },

    { id: 'sp_west_north', zone: ZONE_WEST_ROW, x: -86, z: -46, radius: 4, weight: 1 },
    { id: 'sp_west_yard', zone: ZONE_WEST_ROW, x: -51, z: -30, radius: 3.5, weight: 1 },
    { id: 'sp_west_mid', zone: ZONE_WEST_ROW, x: -86, z: 22, radius: 4, weight: 1 },

    { id: 'sp_east_north', zone: ZONE_EAST_ROW, x: 86, z: -46, radius: 4, weight: 1 },
    { id: 'sp_east_yard', zone: ZONE_EAST_ROW, x: 51, z: -30, radius: 3.5, weight: 1 },
    { id: 'sp_east_mid', zone: ZONE_EAST_ROW, x: 86, z: 22, radius: 4, weight: 1 },

    { id: 'sp_market_west', zone: ZONE_MARKET, x: -40, z: 10, radius: 4, weight: 1 },
    { id: 'sp_market_east', zone: ZONE_MARKET, x: 40, z: 10, radius: 4, weight: 1 },
    { id: 'sp_market_north', zone: ZONE_MARKET, x: 0, z: -34, radius: 4, weight: 1.2 },

    { id: 'sp_apart_west', zone: ZONE_APARTMENTS, x: -43, z: -40, radius: 4, weight: 1 },
    { id: 'sp_apart_east', zone: ZONE_APARTMENTS, x: 43, z: -40, radius: 4, weight: 1 },
    { id: 'sp_apart_north', zone: ZONE_APARTMENTS, x: 0, z: -72, radius: 4, weight: 1 },

    { id: 'sp_depot_west', zone: ZONE_DEPOT, x: -86, z: -98, radius: 4, weight: 1 },
    { id: 'sp_depot_yard', zone: ZONE_DEPOT, x: -30, z: -110, radius: 4, weight: 1 },

    { id: 'sp_sub_east', zone: ZONE_SUBSTATION, x: 86, z: -98, radius: 4, weight: 1 },
    { id: 'sp_sub_yard', zone: ZONE_SUBSTATION, x: 30, z: -110, radius: 4, weight: 1 },
  ],

  wallWeapons: [
    {
      id: 'ww_pistol',
      weapon: 'pistol',
      zone: ZONE_START,
      cost: 500,
      ammoCost: 250,
      x: -11.4,
      y: 1.5,
      z: 72,
      yaw: Math.PI / 2,
    },
    {
      id: 'ww_machete',
      weapon: 'machete',
      zone: ZONE_START,
      cost: 750,
      ammoCost: 0,
      x: 11.4,
      y: 1.5,
      z: 72,
      yaw: -Math.PI / 2,
    },
    {
      id: 'ww_shotgun_west',
      weapon: 'shotgun',
      zone: ZONE_WEST_ROW,
      cost: 1200,
      ammoCost: 600,
      x: -69.2,
      y: 1.5,
      z: -12,
      yaw: Math.PI / 2,
    },
    {
      id: 'ww_rifle_east',
      weapon: 'rifle',
      zone: ZONE_EAST_ROW,
      cost: 1500,
      ammoCost: 750,
      x: 69.2,
      y: 1.5,
      z: -12,
      yaw: Math.PI / 2,
    },
    {
      id: 'ww_shotgun_market',
      weapon: 'shotgun',
      zone: ZONE_MARKET,
      cost: 1200,
      ammoCost: 600,
      x: -20,
      y: 1.5,
      z: -18.2,
      yaw: Math.PI,
    },
    {
      id: 'ww_rifle_depot',
      weapon: 'rifle',
      zone: ZONE_DEPOT,
      cost: 1500,
      ammoCost: 750,
      x: -20,
      y: 1.5,
      z: -93.8,
      yaw: 0,
    },
  ],

  perkMachines: [
    {
      id: 'perk_vitality',
      perk: 'vitality',
      zone: ZONE_MARKET,
      cost: 2500,
      x: 20,
      y: 0,
      z: -19.4,
      yaw: Math.PI,
    },
    {
      id: 'perk_steadyhands',
      perk: 'steadyhands',
      zone: ZONE_EAST_ROW,
      cost: 2000,
      x: 74,
      y: 0,
      z: -34,
      yaw: -Math.PI / 2,
    },
    {
      id: 'perk_secondwind',
      perk: 'secondwind',
      zone: ZONE_APARTMENTS,
      cost: 3000,
      x: -24,
      y: 0,
      z: -46.6,
      yaw: 0,
    },
    {
      id: 'perk_fieldmedic',
      perk: 'fieldmedic',
      zone: ZONE_WEST_ROW,
      cost: 2500,
      x: -74,
      y: 0,
      z: -34,
      yaw: Math.PI / 2,
    },
  ],

  powerSwitch: {
    id: 'power_main',
    zone: ZONE_SUBSTATION,
    x: 62,
    y: 0,
    z: -104,
    yaw: 0,
  },

  rewardMachines: [
    {
      id: 'reward_depot',
      zone: ZONE_DEPOT,
      cost: 950,
      requiresPower: false,
      x: -62,
      y: 0,
      z: -104,
      yaw: 0,
    },
    {
      id: 'reward_apartments',
      zone: ZONE_APARTMENTS,
      cost: 950,
      requiresPower: true,
      x: 24,
      y: 0,
      z: -46.6,
      yaw: 0,
    },
  ],
};
